test

diff --git a/.github/workflows/mac.yml b/.github/workflows/mac.yml
--- a/.github/workflows/mac.yml
+++ b/.github/workflows/mac.yml
@@ -23,67 +23,81 @@ jobs:
             x log init pkg_test
             git clone https://github.com/x-cmd/pkg.git
             x pkg update
-            ___x_cmd_pkg___list "7za" "v0.0.0" "linux/x64" "url.internet" 
-
-
-          # ls pkg/src/osman | for pkg_bin in $(cat); do
-            #   pkg_test:info "$( ___x_cmd_pkg___list "${pkg_bin}" "v0.0.0" "linux/x64" "url.internet" )"
-            #   url="$( ___x_cmd_pkg___list "${pkg_bin}" "v0.0.0" "linux/x64" "url.internet" )"
-            #   pkg_test:info "========================${pkg_bin}====================${url}------------------"
-            #   curl -LO "$url"
-            #   bin_name="$( ___x_cmd_pkg___list "${pkg_bin}" "v0.0.0" "linux/x64" "xbin" )"
-            #   bin_path="$(find ./ -name "${bin_name}")"
-            #   $bin_path --help || {
-            #     pkg_test:error "bin test failed: ${bin_name},path : $bin_path"
-            #     printf "%s\n" "| ${bin_name} | ❌ |" >> ./linux_x64.md
-            #   }
-            # done
-
-  # mac_x64:
-  #   runs-on: mac-latest
-  #   env:
-  #     github_token: ${{ secrets.GITHUB_TOKEN }}
-  #     ssh_key: ${{ secrets.REPO_SSH_KEY }}
-  #     git_user: tzw-my
-  #     git_email: tzw@x-cmd.com
-  #   steps:
-  #     - name: main
-  #       uses: x-cmd/action@main
-  #       with:
-  #         code: |
-  #           x pkg ll | for pkg_bin in $(cat); do
-  #             [ "${pkg_bin}" = "${pkg_bin%%sdkman*}" ] || continue
-  #             [ "${pkg_bin}" = "${pkg_bin%%lang*}" ] || continue
-  #             [ "${pkg_bin}" = "${pkg_bin%%plugin*}" ] || continue
-  #             url="$( ___x_cmd_pkg___list "${app}" "v0.0.0" "darwin/x64" "url.cn" )"
-  #             app_name="${url##*/}"
-  #             mkdir -p "./${app}"
-  #             curl -L "$url" -o "./${app}/${app_name}"
-  #             bin_name="$( ___x_cmd_pkg___list "${app}" "v0.0.0" "darwin/x64" "xbin" )"
-  #             bin_path="$(find ./ -name "${bin_name}")"
-  #             $bin_path --help
-  #           done
-  # windows_x64:
-  #   runs-on: windows-latest
-  #   env:
-  #     github_token: ${{ secrets.GITHUB_TOKEN }}
-  #     ssh_key: ${{ secrets.REPO_SSH_KEY }}
-  #     git_user: tzw-my
-  #     git_email: tzw@x-cmd.com
-  #   steps:
-  #     - name: main
-  #       uses: x-cmd/action@main
-  #       with:
-  #         code: |
-  #           x pkg ll | for pkg_bin in $(cat); do
-  #             [ "${pkg_bin}" = "${pkg_bin%%sdkman*}" ] || continue
-  #             [ "${pkg_bin}" = "${pkg_bin%%lang*}" ] || continue
-  #             [ "${pkg_bin}" = "${pkg_bin%%plugin*}" ] || continue
-  #             url="$( ___x_cmd_pkg___list "${app}" "v0.0.0" "win/x64" "url.cn" )"
-  #             app_name="${url##*/}"
-  #             mkdir -p "./${app}"
-  #             curl -L "$url" -o "./${app}/${app_name}"
-  #             bin_name="$( ___x_cmd_pkg___list "${app}" "v0.0.0" "win/x64" "xbin" )"
-  #             bin_path="$(find ./ -name "${bin_name}")"
-  #             $bin_path --help
-  #           done
+              ls pkg/src/osman | for pkg_bin in $(cat); do
+              pkg_test:info "$( ___x_cmd_pkg___list "${pkg_bin}" "v0.0.0" "linux/x64" "url.internet" )"
+              url="$( ___x_cmd_pkg___list "${pkg_bin}" "v0.0.0" "linux/x64" "url.internet" )"
+              pkg_test:info "========================${pkg_bin}====================${url}------------------"
+              curl -LO "$url"
+              bin_name="$( ___x_cmd_pkg___list "${pkg_bin}" "v0.0.0" "linux/x64" "xbin" )"
+              bin_path="$(find ./ -name "${bin_name}")"
+              $bin_path --help || {
+                pkg_test:error "bin test failed: ${bin_name},path : $bin_path"
+                printf "%s\n" "| ${bin_name} | ❌ |" >> ./linux_x64.md
+              }
+            done
+      - uses: actions/upload-artifact@v3
+          with:
+            path: linux_x64.md
+            name: linux_x64
+  mac_x64:
+    runs-on: mac-latest
+    env:
+      github_token: ${{ secrets.GITHUB_TOKEN }}
+      ssh_key: ${{ secrets.REPO_SSH_KEY }}
+      git_user: tzw-my
+      git_email: tzw@x-cmd.com
+    steps:
+      - name: main
+        uses: x-cmd/action@main
+        with:
+          code: |
+            x log init pkg_test
+            git clone https://github.com/x-cmd/pkg.git
+            x pkg update
+              ls pkg/src/osman | for pkg_bin in $(cat); do
+              pkg_test:info "$( ___x_cmd_pkg___list "${pkg_bin}" "v0.0.0" "darwin/x64" "url.internet" )"
+              url="$( ___x_cmd_pkg___list "${pkg_bin}" "v0.0.0" "darwin/x64" "url.internet" )"
+              pkg_test:info "========================${pkg_bin}====================${url}------------------"
+              curl -LO "$url"
+              bin_name="$( ___x_cmd_pkg___list "${pkg_bin}" "v0.0.0" "darwin/x64" "xbin" )"
+              bin_path="$(find ./ -name "${bin_name}")"
+              $bin_path --help || {
+                pkg_test:error "bin test failed: ${bin_name},path : $bin_path"
+                printf "%s\n" "| ${bin_name} | ❌ |" >> ./darwin_x64.md
+              }
+            done
+      - uses: actions/upload-artifact@v3
+          with:
+            path: darwin_x64.md
+            name: darwin_x64
+  windows_x64:
+    runs-on: windows-latest
+    env:
+      github_token: ${{ secrets.GITHUB_TOKEN }}
+      ssh_key: ${{ secrets.REPO_SSH_KEY }}
+      git_user: tzw-my
+      git_email: tzw@x-cmd.com
+    steps:
+      - name: main
+        uses: x-cmd/action@main
+        with:
+          code: |
+            x log init pkg_test
+            git clone https://github.com/x-cmd/pkg.git
+            x pkg update
+              ls pkg/src/osman | for pkg_bin in $(cat); do
+              pkg_test:info "$( ___x_cmd_pkg___list "${pkg_bin}" "v0.0.0" "win/x64" "url.internet" )"
+              url="$( ___x_cmd_pkg___list "${pkg_bin}" "v0.0.0" "win/x64" "url.internet" )"
+              pkg_test:info "========================${pkg_bin}====================${url}------------------"
+              curl -LO "$url"
+              bin_name="$( ___x_cmd_pkg___list "${pkg_bin}" "v0.0.0" "win/x64" "xbin" )"
+              bin_path="$(find ./ -name "${bin_name}")"
+              $bin_path --help || {
+                pkg_test:error "bin test failed: ${bin_name},path : $bin_path"
+                printf "%s\n" "| ${bin_name} | ❌ |" >> ./win_x64.md
+              }
+            done
+      - uses: actions/upload-artifact@v3
+          with:
+            path: win_x64.md
+            name: win_x64
