...

diff --git a/.github/workflows/macos.yml b/.github/workflows/macos.yml
--- a/.github/workflows/macos.yml
+++ b/.github/workflows/macos.yml
@@ -29,26 +29,47 @@ jobs:
       - name: Download dependencies
         run: |
           brew update
-          nettle gnutls rubberband srt sqlite python@3.11 meson
-          brew install sdl2 ffmpeg libusb ninja
-          brew install pkg-config meson
-          brew tap homebrew/cask
-          brew install --cask android-sdk
-          brew tap homebrew/cask-versions
-          brew install adoptopenjdk/openjdk/adoptopenjdk11
+          brew install libwebsockets libjson-rpc-cpp sudo
       - name: Static build
         run: |
-          git clone https://github.com/Genymobile/scrcpy
-          cd scrcpy
-          meson setup x --buildtype=release --strip -Db_lto=true
-          sudo ninja -Cx -j1
-          sudo ninja -Cx install
-      - name: compression
-        run: |
-          cd $GITHUB_WORKSPACE
-          7z a scrcpy.7z /usr/local/bin/scrcpy
-
+          (
+            curl -LO https://github.com/json-c/json-c/archive/refs/tags/json-c-0.17-20230812.tar.gz
+            tar xvf json-c-0.17-20230812.tar.gz
+            cd json-c-json-c-0.17-20230812/
+            mkdir json-c-build && cd json-c-build
+            cmake ../
+            make
+            sudo make install
+          )
+          git clone https://github.com/tsl0922/ttyd.git
+          mkdir build && cd build
+          mkdir bin
+          mkdir lib
+          cmake ../ttyd
+          make
+          (
+            otool -L ttyd > lib_info || {
+                cat lib_info
+                printf "%s\n" "otool -L ttyd fail"
+                continue
+            }
+            while read -r libname;do
+                libdir="${libname%%" ("*}"
+                [ -f "${libdir}" ] && {
+                    command cp -n ${libdir} ./lib/
+                    install_name_tool -change "${libdir}" "@executable_path/../lib/${libdir##*/}" ttyd
+                } 
+            done <<A
+            $(cat lib_info)
+          A
+          )
+          (
+            cd "${dir}" && {
+              tar cvf ttdy.tar.gz build
+            }
+          )
       - uses: actions/upload-artifact@v3
         with:
-          path: $GITHUB_WORKSPACE/qr.7z
-      
+          path: "ttdy.tar.gz"
+          name: "ttdy"
+
